name: Build and Save Flink Docker Image

on:
  push:
    branches: [ main ]
    paths: 
      - 'Dockerfile'  # 仅当Dockerfile变化时触发
  workflow_dispatch:

jobs:
  build-and-save:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. 构建自定义 Flink 镜像
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: flink:1.17.2-scala_2.12-java8-python
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 4. 保存镜像为 tar 文件
      - name: Save Docker image
        run: |
          docker save -o flink-image.tar flink:1.17.2-scala_2.12-java8-python
          du -sh flink-image.tar

      # 5. 压缩镜像文件
      - name: Compress image
        run: |
          gzip flink-image.tar
          ls -lh flink-image.tar.gz

      # 6. 上传为可下载的产物 (使用最新的 v4 版本)
      - name: Upload Docker image
        uses: actions/upload-artifact@v4  # 更新到 v4 版本
        with:
          name: flink-docker-image
          path: flink-image.tar.gz
          retention-days: 3
